name: Hello World!

on: 
  push:
    branches: [main]
    paths-ignore:
      - ".github/workflows/*"
  pull_request: 
    branches: [main]

  repository_dispatch:
    types: ["on-demand-test"]

jobs:
  echo-vars:
    if: github.event.client_payload.state == 'completed' and github.event.client_payload.job_name == 'echo-vars'
    env:
      PACKAGE_PATH: '.'
    runs-on: ubuntu-latest
    steps:
      - name: Echo Environment Variables
        env:
          APP_VERSION: '1.0.0'
          APP_NAME: 'MyApp Echo'
          RUNNER_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "GITHUB_REPOSITORY: ${{ github.repository }}"
          echo "GITHUB_REF: ${{ github.ref }}"
          echo "GITHUB_SHA: ${{ github.sha }}"
          echo "GITHUB_ACTOR: ${{ github.actor }}"
          echo "GITHUB_EVENT_NAME: ${{ github.event_name }}"
          echo "GITHUB_EVENT_PATH: ${{ github.event_path }}"
          echo "GITHUB_WORKFLOW: ${{ github.workflow }}"
          echo "GITHUB_RUN_ID: ${{ github.run_id }}"
          echo "GITHUB_RUN_NUMBER: ${{ github.run_number }}"
          echo "GITHUB_JOB: ${{ github.job }}"
          echo "GITHUB_ACTION: ${{ github.action }}"
          echo "GITHUB_API_URL: ${{ github.api_url }}"
          echo "GITHUB_SERVER_URL: ${{ github.server_url }}"
          echo "GITHUB_GRAPHQL_URL: ${{ github.graphql_url }}"
          echo "PACKAGE_PATH: $PACKAGE_PATH"
          echo "this application name: $APP_NAME version: $APP_VERSION"
          echo "$RUNNER_CONTEXT"
          echo "Database password: ${{ secrets.DB_PASSWORD }}"
          
  hello-job:
    if: github.event.client_payload.state == 'completed' and github.event.client_payload.job_name == 'hello-job'
    name: Test Job1
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "Hello Github Actions! na"
        
      - name: Show payload from external trigger
        run: |
          echo "Trigger Event: ${{ github.event_name }}"
          echo "Client Payload Message: ${{ github.event.client_payload.message }}"
          echo "Client Payload State: ${{ github.event.client_payload.state }}"

  second-job:
    if: github.event_name != 'repository_dispatch'
    runs-on: windows-latest
    needs: hello-job
    steps:
      - name: Run on Windows
        run: echo "This job is running on ${{ runner.os }}"